export const FETCH_FORECAST = "FETCH_FORECAST";
export const FETCH_HISTORY = "FETCH_HISTORY";
export const SELECT_PORTFOLIO = "SELECT_PORTFOLIO";
export const COMPUTE_PORTFOLIO = "COMPUTE_PORTFOLIO";
export const SET_HISTORY_RANGE = "SET_HISTORY_RANGE";
export const FETCH_PORTFOLIO_METADATA = "FETCH_PORTFOLIO_METADATA";
